### ISSUE TITLE
Vue 2 tag

### ISSUE THREAD

**Issue by luizfeer** [hansonGong/mathjax-vue#2]
How to configure to work on a specific element in a component?
Ex:
`<span class="math-text">$$ x_a+y^2 $$</span>`

**Comment by hansonGong** [comment]
However, the use of mathjax-vue can only be started after initmathjax is executed。

function onMathJaxReady() {
  const elements = getElementsByClassName('math-text"')
  renderByMathjax(elements)
}

initMathJax({}, onMathJaxReady)

OR

initMathJax()
// But when mathjax loads successfully
renderByMathjax(getElementsByClassName('math-text"'))

**Comment by hansonGong** [comment]
I'm sorry I didn't help you in time.

**Comment by luizfeer** [comment]
Work 🎉🎉
it's possible to change the formula template?
EX:
`<span class="math-text">\(77+222 \)</span>`

**Comment by hansonGong** [comment]
Of course, but you can't use '\\' because it is an escape character and can be changed to '/'

const options = {
  tex: {
    inlineMath: [['/(', '/)']],
  },
}

initMathJax(options, onMathJaxReady);
