### ISSUE TITLE
Vue build打包之后，插件无法解析公式

### ISSUE THREAD

**Issue by WuSa12956** [hansonGong/mathjax-vue#3]
如题，插件在本地运行良好，但是运行`npm run build`之后，线上的数学公式无法解析，还是原有markdown的格式。请问下这是什么原因？还是插件自身的bug？

**Comment by hansonGong** [comment]
> 如题，插件在本地运行良好，但是运行`npm run build`之后，线上的数学公式无法解析，还是原有markdown的格式。请问下这是什么原因？还是插件自身的bug？

有链接看下或者贴下具体代码看下？
