### ISSUE TITLE
rendering with reactivity

### ISSUE THREAD

**Issue by luizalmeida77** [hansonGong/mathjax-vue#4]
I understand that renderByMathjax receives the elements to render the formulas, and the solution is to look inside the $el or document, but through the reactivity the documen is always being modified by vue, and new formulas need to be rendered, it seems like a waste of performace having to read the entire document when there are changes.
Is it not possible to send the text to be rendered and get the html already transpiled back?
Ex:
```
const textFormula = '<span class="math-tex">\( x_a+y^3 a \)</span>'
const html = renderByMathjax(textFormula )
```
Return:
html = `<span class="math-tex"><mjx-container><svg> ....... </svg></mjx-container></span>`

or is there any other solution for not having to render the text and then call the renderByMathjax method?
this causes a bad rederization effect and a large amount of time.

**Comment by hansonGong** [comment]
You can try
`
const el = document.createElement('span')
el.innerHTML = '\( x_a+y^3 a \)'
renderByMathjax(el);
`
Is the el you want?

**Comment by luizalmeida77** [comment]
i try:
``` 
 async renderMath (html) {
      const template = document.createElement('template')
      template.innerHTML = html
      const elements = template.content.querySelector('.math-tex')
      this.renderByMathjax(elements)
      await this.$nextTick()
      console.log('afterrendering', template.content.firstElementChild.innerHTML)
      return template.content.firstElementChild.innerHTML
    },
```

```
const textFormula = '<span class="math-tex">\( x_a+y^3 a \)</span>'
const html = await this.renderMath(textFormula)
```
works but return mangled svg.
in view:
![image](https://user-images.githubusercontent.com/87023894/148568622-33bde244-0995-4e61-85e4-d6967b46c7a7.png)
in console:
![image](https://user-images.githubusercontent.com/87023894/148568686-f196f6b3-5384-4a6e-bb03-57047c5a1b87.png)

**Comment by hansonGong** [comment]
There seems to be no good solution to this problem, this is the problem of mathJax processing nodes, you can try
`
const elements = template.content.querySelector('.math-tex')
document.body.appendChild(elements)
this.renderByMathjax(elements)
document.body.removeChild(elements)
`
It will be normal, but it will manipulate the DOM multiple times, so it is better to leave it to Vue.
