### ISSUE TITLE
Math Formula does not work in chrome 98

### ISSUE THREAD

**Issue by superdiazzz** [hansonGong/mathjax-vue#5]
No formula appear, only keyboard general type, for ex: x^2+y^2  it won't convert to formula
![Screen Shot 2022-03-06 at 13 15 47](https://user-images.githubusercontent.com/10770867/156911715-538f6cd2-ef99-4c00-9929-f72bef6cde38.png)

**Comment by hansonGong** [comment]
I am sorry! Cannot replying to you in time. Can I see your code? It should be the issue of the initmathjax function

**Comment by superdiazzz** [comment]
@hansonGong actually that are running in your post codepen [https://codesandbox.io/s/funny-silence-cgzn5](https://codesandbox.io/s/funny-silence-cgzn5)
![Screen Shot 2022-03-09 at 09 23 17](https://user-images.githubusercontent.com/10770867/157360219-1122a885-31c6-429f-bf87-de60720091c8.png)

**Comment by hansonGong** [comment]
I suggest you add a debugger in 'onMathJaxReady' to see if it has been runed.  Or check whether your network can be accessed normally https://cdn.bootcdn.net/ajax/libs/mathjax/3.2.0/es5/tex-chtml.js
